package net.brainscorch.BRID.Client;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;

public class BRIDClient extends javax.swing.JFrame {
	
	private final String	STATUS_REQUEST = "#STATUS#";
	private final String	DATABASE_DUMP = "#DBDUMP#";
	
	private CommandSender	cSend;
	private ImageSender	iSend;
	private StatusListener	sListen;
	private ServerInformation sInfo;
	
	/**
	 * Creates new form BRIDClient
	 */
	public BRIDClient() {
		super("BRID Client");
		initComponents();
		
		sInfo = new ServerInformation();
		
		cSend = new CommandSender();
		iSend = new ImageSender();
		
		sListen = new StatusListener(this);
		sListen.start();
		
		
		jTextFieldServerAddress.getDocument().addDocumentListener(new DocumentListener() {
			@Override
			public void changedUpdate(DocumentEvent e) { onChange(); }
			@Override
			public void removeUpdate(DocumentEvent e) { onChange(); }
			@Override
			public void insertUpdate(DocumentEvent e) { onChange(); }
			
			public void onChange() {
				cSend.setStrServerAddress(jTextFieldServerAddress.getText());
				iSend.setStrServerAddress(jTextFieldServerAddress.getText());
				System.out.printf("Server Address is now: %s\n", cSend.getStrServerAddress());
			}
		});
	}
	
	public void setScreenDimension(Dimension d) {
		String dimensionText = String.format("%dx%d", (int)d.getWidth(), (int)d.getHeight());
		jLabelDimensions.setText(dimensionText);
		Integer ratio = gcd((int)d.getWidth(), (int)d.getHeight());
		String aspectRatio = String.format("(%d:%d)", (int)(d.getWidth()/ratio), (int)(d.getHeight()/ratio));
		//System.out.printf("Calculated Ratio: %s\n", aspectRatio);
		jLabelDimensionsRatio.setText(aspectRatio);
	}
	
	private int gcd(int a, int b) { return b==0 ? a : gcd(b, a%b); }

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldServerAddress = new javax.swing.JTextField();
        jButtonConnect = new javax.swing.JButton();
        jLabelThumbnail = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelDimensions = new javax.swing.JLabel();
        jLabelDimensionsRatio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelScaleFactor = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelImageSize = new javax.swing.JLabel();
        jButtonSelectImage = new javax.swing.JButton();
        jLabelImageSelection = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jButtonSendImage = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonDBDump = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Server Address:");

        jTextFieldServerAddress.setText("localhost");
        jTextFieldServerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldServerAddressActionPerformed(evt);
            }
        });

        jButtonConnect.setText("Get Info");
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        jLabelThumbnail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/brainscorch/BRID/Client/img/nopic.png"))); // NOI18N
        jLabelThumbnail.setText("jLabel4");
        jLabelThumbnail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Thumbnail:");

        jLabel6.setText("Dimensions:");

        jLabelDimensions.setText("-");

        jLabelDimensionsRatio.setText("(-)");

        jLabel9.setText("Image Scale:");

        jLabelScaleFactor.setText("-");

        jLabel11.setText("Image Size:");

        jLabelImageSize.setText("-");

        jButtonSelectImage.setText("Select Image");
        jButtonSelectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectImageActionPerformed(evt);
            }
        });

        jLabelImageSelection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageSelection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/brainscorch/BRID/Client/img/nopic.png"))); // NOI18N
        jLabelImageSelection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Preview:");

        jButtonSendImage.setText("Send Image");
        jButtonSendImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendImageActionPerformed(evt);
            }
        });

        jButtonDBDump.setText("Debug DB Dump");
        jButtonDBDump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDBDumpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelScaleFactor)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelDimensions)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelDimensionsRatio))
                                    .addComponent(jLabelImageSize))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelImageSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelThumbnail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldServerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSelectImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDBDump, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jButtonSendImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldServerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConnect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDBDump))
                    .addComponent(jLabelThumbnail, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelDimensions)
                    .addComponent(jLabelDimensionsRatio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabelImageSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelScaleFactor))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jButtonSelectImage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSendImage))
                    .addComponent(jLabelImageSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	private void jTextFieldServerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldServerAddressActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jTextFieldServerAddressActionPerformed

	private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
		// TODO add your handling code here:
		cSend.sendMessageToServer(STATUS_REQUEST);
	}//GEN-LAST:event_jButtonConnectActionPerformed

	private void jButtonSelectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectImageActionPerformed
		// TODO add your handling code here:
		JFileChooser fChooser = new JFileChooser();
		FileNameExtensionFilter fFilter = new FileNameExtensionFilter("JPG Images", "jpg");
		fChooser.setFileFilter(fFilter);
		int fReturnVal = fChooser.showOpenDialog(this);
		if (fReturnVal == JFileChooser.APPROVE_OPTION) {
			System.out.printf("New file chosen: %s\n", fChooser.getSelectedFile().getAbsolutePath());
			iSend.setImageFile(fChooser.getSelectedFile());
			try {
				BufferedImage bImage = ImageIO.read(iSend.getImageFile());
				float aspectRatio = bImage.getWidth() / bImage.getHeight();
				Image sImage;
				if (aspectRatio >= (16/9)) {
					float scaleFactor = (float)160 / (float)bImage.getWidth();
					//System.out.printf("Scale Factor: x %.3f\n", scaleFactor);
					//System.out.printf("New Image Dimensions: %dx%d\n", Math.round(bImage.getHeight()*scaleFactor), 90);
					sImage = bImage.getScaledInstance(160, Math.round(bImage.getHeight()*scaleFactor), Image.SCALE_SMOOTH);
					
				}
				else {
					float scaleFactor = (float)90 / (float)bImage.getHeight();
					//System.out.printf("Scale Factor: x %.3f\n", scaleFactor);
					//System.out.printf("New Image Dimensions: %dx%d\n", Math.round(bImage.getWidth()*scaleFactor), 90);
					sImage = bImage.getScaledInstance(Math.round(bImage.getWidth()*scaleFactor), 90, Image.SCALE_SMOOTH);
				}
				
				ImageIcon icon = new ImageIcon(sImage);
				jLabelImageSelection.setIcon(icon);
			}
			catch (IOException e) {
				System.err.printf("Error: could not read image \"%s\"\n", iSend.getImageFile().getAbsoluteFile());
			}
			
			
		}
	}//GEN-LAST:event_jButtonSelectImageActionPerformed
	
	private void jButtonSendImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendImageActionPerformed
		// TODO add your handling code here:
		//System.out.println(new File(".").getAbsolutePath());
		iSend.sendImageToServer();
	}//GEN-LAST:event_jButtonSendImageActionPerformed

	private void jButtonDBDumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDBDumpActionPerformed
		// TODO add your handling code here:
		cSend.sendMessageToServer(DATABASE_DUMP);
	}//GEN-LAST:event_jButtonDBDumpActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
		 * If Nimbus (introduced in Java SE 6) is not available, stay
		 * with the default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(BRIDClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(BRIDClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(BRIDClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(BRIDClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable() {

			@Override
			public void run() {
				new BRIDClient().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonDBDump;
    private javax.swing.JButton jButtonSelectImage;
    private javax.swing.JButton jButtonSendImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDimensions;
    private javax.swing.JLabel jLabelDimensionsRatio;
    private javax.swing.JLabel jLabelImageSelection;
    private javax.swing.JLabel jLabelImageSize;
    private javax.swing.JLabel jLabelScaleFactor;
    private javax.swing.JLabel jLabelThumbnail;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldServerAddress;
    // End of variables declaration//GEN-END:variables
}
